const EPS = [
{
  id: 1,
  title: "Episode 01",
  steps: [
    "After intro cut scene: <i>Gesture: The Ring</i>",
    "Corpse on the right: <i>Tarnished's Wizened Finger</i>",
    "Open the double doors, move up and get killed by Grafted Scion",
    { t:'tip', text:"It is possible to kill the Grafted Scion now, but it's very difficult and not worth the trouble. We'll be back here much later to get our revenge." },
    "Cut scene → <i>3x Flask of Crimson Tears</i> + <i>1x Flask of Cerulean Tears</i>",
    "Jump down the hole to the right",
    "Move up → Site of Grace: Cave of Knowledge → Rest",
    "Do the Tutorial area",
    { t:'tip', text:"Unsheathe is an amazing Ash of War" },
    { t:'tip', text:"Use Jump Attacks vs Shield enemies to break their posture and get a critical hit" },
    { t:'tip', text:"Stealthing and backstabs — sneak behind enemies for free damage" },
    { t:'tip', text:"Spacing — let enemies swing first, then backstab" },
    { t:'tip', text:"Parrying — great when it works, but requires perfect timing and knowing the enemy's movesets. We'll rarely use it in this guide and rely on much safer mechanics instead." },
    "At the end of Tutorial area: <i>Gesture: Strength!</i>",
    "Open double doors → Site of Grace: Stranded Graveyard → Rest",
    "Move up, loot corpse on the right: <i>Finger Severer</i> + <i>Tarnished's Furled Finger</i>",
    "Take lift up and exit",
    "Talk to Varré 3 times",
    "Activate Site of Grace: The First Step",
    "Drop down to the right: <i>Small Golden Effigy</i>",
    "Head North to Church of Elleh — avoid the knight rider in golden armor",
    "<i>Golden Rune [2]</i> (in front of the church)",
    "Activate Site of Grace: Church of Elleh",
    "Talk to Kalé → \"About Kalé\" → buy <i>Crafting Kit</i> (300 Runes)",
    "Next to Kalé on the anvil: <i>Smithing Stone [1]</i>",
    "Run North along the path through the woods: <i>4x Kukri</i> (west side of the path)",
    "<i>4x Ruin Fragment</i> (east side of the path on some ruins)",
    { t:'tip', text:"Ruin Fragments are crafting materials that respawn every time you rest at a grace — just grab them on the way whenever you see them. They won't be listed each time." },
    "Go left around the big camp → Site of Grace: Gatefront",
    "Open inventory and use our keepsake: <i>Lands Between Rune</i> — also use the <i>Golden Rune [2]</i> we just picked up",
    "Rest at the grace to trigger cut scene with Melina → \"Accept\"",
    "<i>Spectral Steed Whistle</i>",
    "Level up: put all runes into Vigor",
    { t:'tip', text:"For now our priority is to have enough health to not die every time we get hit — so Vigor it is!" }
  ]
}
,
{
  id: 2,
  title: "Episode 02",
  steps: [
    "Clear Gatefront Ruins — use a mix of stealthing (night time helps) and bow pulling",
    "<i>Map: Limgrave, West</i> (stele at the start of the camp)",
    "<i>3x Ruin Fragment</i> (corpse southwestern side of camp)",
    "<i>Longsworn's Greatsword</i> (chariot gate side of camp)",
    "<i>Flail</i> (chariot northeast of camp)",
    "Take stairs down and open chest: <i>Whet Knife</i> + <i>Ash of War: Storm Stomp</i>",
    "Hotkey your Spectral Steed Whistle and use it to summon Torrent",
    "Southeast along the road → Site of Grace: Agheel Lake North → Rest and level up",
    "All into Vigor until 20",
    { t:'tip', text:"Stats goals by priority: Vigor 20 → Strength 18 → End 15 → Dex 17 → Vigor 25 → End 20" },
    "Pass time until morning (roads are safer during daytime)",
    "East/Southeast: find Boc the Seamster by hitting a suspicious bush",
    "Talk to Boc the Seamster 2x → <i>10x Mushroom</i>",
    "Talk to Boc once more",
    "<i>Arteria Leaf</i> (southwest a few steps)",
    "East until bridge → <i>Ash of War: Determination</i> (kill Grey Scarab)",
    "<i>Smithing Stone [1]</i> (corpse on bridge's edge)",
    "Southeast past Waypoint Ruins to a graveyard — kill wolf pack then loot the coffins: <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [3]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>",
    "Warp to Church of Elleh",
    "Talk to Renna → \"I can call the spectral steed\" → <i>Spirit Calling Bell</i> + <i>Lone Wolf Ashes</i>",
    "Talk to Renna again until she vanishes",
    "Talk to Kalé",
    "Talk 2x (he'll tell you about his people)",
    "Buy from Kalé: <i>Nomadic Warrior's Cookbook [1]</i>",
    { t:'tip', text:"Don't worry about the other cookbooks, we'll buy them later, we won't need them any time soon, our runes will be better spent elsewhere" },
    "Upgrade <i>Uchigatana +1</i> (at the anvil)",
    "Warp to Gatefront",
    "Ride northwest straight through the gate, loot corpse on the way: <i>Lump of Flesh</i>",
    "Keep going until you see a small golden tree on the right side of the path: <i>Golden Seed</i>",
    "Further up the path → Site of Grace: Stormhill Shack → Rest → Add Charge to Flask",
    "<i>Stonesword Key</i> (few steps southeast, corpse up wooden structure)",
    "Inside the shack, talk to Roderika 3x → <i>Gesture: Sitting Sideways</i> + <i>Spirit Jellyfish Ashes</i>"
  ]
},
{
  id: 3,
  title: "Episode 03",
  steps: [
    "From Stormhill Shack",
    "South on top of ruins: <i>Crossed Legs</i>",
    "Southwest to the edge to find a big Sundial: <i>Starlight Shard</i>",
    "Northwest in the forest, all the way to the northwest corner: <i>Smithing Stone [1]</i>",
    "East in the forest, through Jellyfish camp, just loot and run: <i>3x Bloodrose</i> + <i>Godrick Soldiers Ashes</i> + <i>3x Magic Grease</i>",
    "East, drop down and then northeast back to Stormhill Shack",
    "Pass time until morning",
    "Southeast to dead guy sitting on chair in an open field: <i>3x Smithing Stone [1]</i>",
    "Head north to upper layer of the hill then east along the edge: <i>Strength-Knot Crystal Tear</i>",
    "Go backwards and down the lower cliff level, then east to: <i>5x Fire Arrows</i>",
    "Go east/southeast to a graveyard (watch out bombs): <i>Golden Rune [3]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [5]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>",
    "North/Northeast → Site of Grace: Warmaster's Shack",
    "Talk to Bernhal",
    "\"My Faith holds firm\"",
    "Talk",
    "Purchase: <i>Ash of War: No Skill</i> (600 Runes)",
    "A few steps east/northeast around a tree: <i>3x Root Resin</i> (these can be farmed by resting at the nearby grace, very useful crafting material)",
    "Go back to the grace, use all golden runes and level up — reach Vigor 20 or close",
    { t:'tip', text:"Stats goals by priority: Vigor 20 → Strength 18 → End 15 → Dex 17 → Vigor 25 → End 20" },
    "Pass time until morning",
    "South to troll area — have them destroy the glowing stone to get: <i>4x Smithing Stone [1]</i> + <i>1x Smithing Stone [2]</i>",
    "Northeast to an item under a troll: <i>Beast Liver</i>",
    "North to encampment — hotkey Lone Wolf Ashes and summon them — clear the camp: <i>Exalted Flesh</i> (corpse near tent on the right) + <i>Beast Crest Heater Shield</i> (chest on opposite side of camp)",
    "Clear the rest of the camp with the help of your Wolves",
    "East back on the trail → Site of Grace: Saintsbridge",
    "Cross bridge: <i>2x Smithing Stone [1]</i> (corpse)",
    "Merchant to the right past bridge: buy <i>Nomadic Warrior's Cookbook [3]</i> + <i>Cracked Pot</i>",
    "Southeast to a big two-part ruins, at the foot of second one loot 3 plants: <i>3x Triny's Lily</i>",
    "West/southwest, drop down a couple of cliffs then south to a shack: <i>Smithing Stone [1]</i> + <i>\"Homing Instinct\" Painting</i>",
    "Site of Grace: Artist's Shack",
    "Northeast, drop down another cliff and further northeast to a graveyard: <i>Golden Rune [6]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [4]</i>, <i>Fevor's Cookbook [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [4]</i>, <i>Golden Rune [1]</i>",
    "North/Northeast — drop down safely using tombstones sticking out of the cliff wall",
    "Drop down the next cliff using another tombstone, land in the river with bear and wolves fighting — quickly loot corpse and go back: <i>Smithing Stone [2]</i>",
    "Follow the river, stick to your left — further east find Grey Scarab on northern river bank: <i>Ash of War: Sacred Blade</i>",
    "Further east by a broken cart: <i>Neutralizing Boluses</i>",
    "Go back west along the cliff edge until you can safely drop down to reach the church below",
    "Inside the church: <i>Crimson Crystal Tear</i> + <i>Flask of Wondrous Physicks</i> + <i>Sacred Tear</i>",
    "Site of Grace: Third Church of Marika",
    "Rest and talk to Melina",
    "\"I'm interested\""
  ]
},
{
  id: 4,
  title: "Episode 04",
  steps: [
    "Warp to Stormhill Shack",
    "Northwest follow path towards castle, kill Grey Scarab: <i>Ash of War: Wild Strikes</i>",
    "North to ruined bridge, talk to old lady",
    "\"Show hands\"",
    "Further up the bridge: <i>Nomadic Warrior's Cookbook [7]</i>",
    "Check video for next part, it's a long way around Stormveil Castle.",
    "Jump down and follow a very long secret path, run past wolves, activate (but don't rest) Site of Grace: Lake-Facing Cliffs",
    "Further West/Southwest to reach Church of Irith: <i>Sacred Tear</i>",
    "Talk to Thops",
    "\"Donate 10 Runes\"",
    "Talk",
    "About the glintstone key",
    "West take the path down, go around the big encampment and activate (don't rest) Site of Grace: Liurna Lake Shore",
    "Talk to Nomadic Merchant: buy <i>Lantern</i> (1800 Runes — use Golden Runes if needed)",
    "Ride north to the map stele, loot and keep going north: <i>Map: Liurnia, East</i>",
    "Keep going north for a long while into the lake (check video to see exactly where)",
    "You'll reach the eastern shore, activate (but don't rest) Site of Grace: Eastern Liurnia Lake Shore",
    "East path then south until Grey Scarab: <i>Somber Smithing Stone [3]</i> (if scarab escapes no problem, do next step and rest at the grace to respawn it)",
    "Southeast to Carian Study Hall, enter building: Site of Grace: Study Hall Entrance → Rest",
    "Melina will talk to you",
    "\"Go to the Roundtable Hold\"",
    "Achievement Unlocked: Roundtable Hold",
    "Talk to everyone in the first room, counter-clockwise:",
    "Talk 2x to Sir Gideon Offnir, the All-Knowing",
    "Talk 1x to Roderika",
    "Talk to Brother Corhyn",
    "\"I see it\"",
    "<i>Gesture: Prayer</i>",
    "Go to hallway next to Corhyn",
    "Talk to masked man leaning against the column",
    "<i>Gesture: What do you want?</i>",
    "Talk to Twin-Maiden Husks in the next room and buy: <i>White Cipher Ring</i>",
    "Back to round table room, enter room left of the fireplace",
    "Talk to Smithing Master Hewg",
    "Upgrade <i>Uchigatana +4</i> (1500 Runes needed)",
    "\"About Roderika\"",
    "\"About the Chains on your legs\"",
    "\"You're a prisoner?\"",
    "Talk to Fia",
    "\"Let her hold you\" → <i>Baldachin's Blessing</i>",
    "Go to your inventory and use the <i>Baldachin's Blessing</i> (removes the HP debuff from the hug)",
    "Go back to the roundtable, talk to Roderika",
    "\"Tell her about what the blacksmith said\"",
    "Go back to Smithing Master Hewg",
    "\"About Roderika\"",
    "\"Would you watch over Roderika?\"",
    "\"It's what she wants\"",
    "Go talk to Roderika again",
    { t:'tip', text:"The next time we come back here, Roderika will have become a Spirit Tuner and we'll be able to upgrade our Summon Ashes" }
  ]
},
{
  id: 5,
  title: "Episode 05",
  steps: [
    "Warp to Third Church of Marika",
    "Equip <i>Beast Crest Heater Shield</i> (instead of our crappy shield)",
    "Rest",
    "Flasks: Upgrade Flask to +2",
    "Mix Wondrous Physiks: <i>Crimson Crystal Tear</i> + <i>Strength-knot Crystal Tear</i>",
    "Ash of War: No Skill on Beast Crest Heater Shield (unless you like parrying and feel confident with it)",
    "Southwest under the bridge, summon Wolves, clear the demi-human gang",
    { t:'tip', text:"Check video for combat tips about: Shield and Guard Counter, No Skill Ash of War" },
    "On the other side of bridge by a broken cart: <i>Magic Grease</i>",
    "Go up bridge, talk to Kenneth Haight 3x",
    "Southwest along the road to find Site of Grace: Mistwood Outskirts",
    "Pass time until morning",
    "Southeast to pond in the middle of Mistwoods — grab everything while running and run away east: <i>Golden Rune [5]</i>, <i>5x Throwing Knives</i>, <i>Gold-Tinged Excrement</i>",
    "East to map stele: <i>Map of East Limgrave</i>",
    "Southwest next to Runebear scratching tree, grab and run south: <i>Nomadic Warrior's Cookbook [4]</i>",
    "South follow path until cart with ambush by 4 demi-humans: <i>3x Thin Beast Bones</i>",
    "<i>Golden Rune [1]</i> (west off the trail, post guarded by 2 Gargoyles)",
    "East/Southeast to find and kill grey scarab: <i>Ash of War: Ground Slam</i>",
    "East/northeast to Minor Erdtree: <i>Spiked Cracked Tear</i> + <i>Greenspill Crystal Tear</i>",
    "Make a lap around the tree to grab a bunch of flowers",
    "Also kill crimson scarab if you need to refill your flasks",
    "Get back on path head southwest to Mistwood Ruins. You should hear Wolves Howling.",
    "Watch out for the giant bear sleeping, sneak to avoid waking it up",
    "<i>Golden Rune [2]</i> (southwest part of the ruins)",
    "<i>Smithing Stone [2]</i> (chest inside tower)",
    "<i>Axe Talisman</i> (chest downstairs next to sleeping bear)",
    "Equip <i>Axe Talisman</i>",
    "Summon Torrent to ride out of the cave past the bear and go west",
    "West of Mistwood Ruins, up on a small rocky hill, by a large tombstone: <i>Sacrificial Twig</i> (guarded by Specters and Flowers, just loot and ride away)",
    "East/Southeast back to the road, you'll see a glowing message sign — kill the demi-humans ambush",
    "Northeast into the woods to find a Nomadic Merchant, purchase: <i>Nomadic Warrior's Cookbook [3]</i> (1500 Runes) + <i>Armorer's Cookbook [5]</i> (2000 Runes)",
    "Get back on path",
    "Southeast all the way to Site of Grace: Fort Haight West → Rest",
    "Fort Haight (Run past barricades, lose aggro with horse)",
    { t:'tip', text:"Check video on how to clear this castle safely. First clear the outer part, including the Mad Pumpkin Head." },
    "<i>Golden Seed</i> (small golden tree outside the castle)",
    "Go inside fort, careful with Fire Pot Throwers and explosive barrels — if possible, snipe them from afar with bow: <i>3x Bloodrose</i> (corpse in courtyard — more Bloodrose flowers in the courtyard, can be farmed by resting at a grace)",
    "<i>Nomadic Warrior's Cookbook [6]</i> (inside fort, watch out for fire tossers and explosive barrels)",
    "<i>Ash of War: Bloody Slash</i> (defeat knight on top — summon Wolves)",
    "<i>5x Bloodrose</i> (corpse up the rampart where knight miniboss was)",
    "Opposite wooden walkway, in a nook to the left: <i>Smithing Stone [1]</i>",
    "Inside the tower, ladder up to the top: <i>Dectus Medallion (Left)</i>",
    "Warp to Fort Haight West",
    "Southwest to beach, defeat Giant Land Octopus (check video for combat trick to easily beat these)",
    "<i>Golden Rune [1]</i> (corpse behind octopus)",
    "Further southwest to graves: <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [3]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [4]</i>, <i>Golden Rune [1]</i>",
    "Warp to Saintsbridge",
    "West up the path then turn northeast up the hill to find Catacombs door",
    "Enter to find Site of Grace: Deathtouched Catacombs"
  ]
},
{
  id: 6,
  title: "Episode 06",
  steps: [
    { t:'sec', text:"Deathtouched Catacombs" },
    "Use all Golden Runes available",
    "Rest and level up",
    { t:'tip', text:"Stats goals by priority: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "Equip <i>Lordsworn's Greatsword</i> (unless you don't have enough runes to reach 16 STR, in that case equip any other weapon you have the reqs for — if you don't have any other options, stick with the Uchigatana)",
    "Flasks: Add charge to flask",
    "Ash of War: <i>Lordsworn's Greatsword</i> (or any other weapon you can equip) → Sacred Blade → Holy (very efficient against skeletons and all undead types, prevents them from resuscitating)",
    { t:'tip', text:"Don't apply Sacred Blade on our Uchigatana, or we won't have the Unsheathe Ash of War anymore" },
    "Clear the first room, 4 skeletons (if you don't have Sacred Blade, kill the enemies then hit them before they resuscitate): <i>2x Grave Glovewort [1]</i> (1st room)",
    "Under the stairs, west narrow tunnel: <i>Grave Glovewort [1]</i>, <i>Grave Violet</i>, <i>Uchigatana</i>, <i>Grave Glovewort [1]</i>",
    "Defeat archer up top — don't drop down, safer to go back and take the stairs down — clear the room methodically: <i>1x Grave Glovewort [1]</i>",
    "West hallway to next room: <i>3x Blood Rose</i> (corpse to the right), <i>1x Grave Violet</i>",
    "Pull Lever",
    "Go back to Lost Grace and rest",
    "Re-equip <i>Uchigatana +4</i>",
    "Go to yellow fog and prepare for Boss: Black Assassin",
    "Pop Flask of Physiks before going in",
    "Enter, summon wolves, let them get the aggro — use charged attacks / Unsheathe — if he attacks you, keep shield up and use strong counter",
    "<i>Assassin's Crimson Dagger</i>",
    "<i>1x Deathroot</i> (chest)",
    "<i>Root Resin</i> (right corner)",
    "<i>Root Resin</i> (left corner)",
    "Exit",
    "Northeast, go under giant bridge to defeat Golem (check video for an easy strategy to beat those enemies)",
    "A few steps from the Golem, loot corpse sitting on top of statue rubbles: <i>Lance Talisman</i>",
    "South until cliff edge, defeat small group: <i>Golden Rune [3]</i>",
    "South and then east to the other side of the ravine — find Alexander the pot warrior",
    "\"Help him out\"",
    "<i>Gesture: Triumphant Delight</i>",
    "Talk to Alexander → <i>Exalted Flesh</i>",
    "Talk to Alexander again",
    "Warp to Church of Elleh",
    "Talk to Kalé",
    "About the Howling in Mistwood",
    "<i>Gesture: Finger Snap</i>",
    "Northwest to find a catacombs door at the foot of the cliff",
    "Site of Grace: Stormfoot Catacombs",
    "Rest and level up",
    { t:'tip', text:"Stats reminder: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    { t:'sec', text:"Stormfoot Catacombs" },
    "First room northwest, ambush Imp on the left — loot corpse: <i>2x Root Resin</i>",
    "Northeast hallway to boss door room, plant to the right: <i>Grave Glovewort [1]</i>",
    "Next room hide under the archways to avoid projectiles from imp above — kill imp below, loot plant: <i>Grave Glovewort [1]</i>",
    "Through narrow corridor, disable fire pillar trap with bow (check video to see how to disable these traps)",
    "Loot corpse behind fire trap: <i>Prattling Pate \"Hello\"</i>",
    "Backtrack and disable another fire pillar southeast corridor",
    "Behind trap, bow pull 2 imps up on the wall, kill them before moving up and killing 3 more imps (2 left 1 right): <i>3x Smoldering Butterfly</i>, <i>Ghost Glovewort</i>",
    "Backtrack and southwest ladder up — imp left as you enter, another imp opposite side of the room — loot plant: <i>Grave Glovewort [1]</i>",
    "Southwest hallway to room, imp ambush on the right + one more imp: <i>Grave Glovewort [1]</i>, <i>Wandering Nobles Ashes</i>",
    "Backtrack to previous room, drop down on upper ledge south, kill imp: <i>Grave Glovewort [1]</i>",
    "Pull lever",
    "Drop down, stairs back up to boss door room — if needed, go back to the grace to refill your flasks",
    "Prepare for boss Erdtree Burial Watchdog",
    "Pop Flask before entering",
    "Enter, summon Wolves, let them get aggro and use Unsheathe / Charged Attacks",
    "<i>Noble Sorcerer Ashes</i>",
    "East along the wall, go around ruins, then stick to the wall to find a Cave entrance",
    "Site of Grace: Groveside Cave",
    "Rest and level up",
    { t:'tip', text:"Stats priority reminder: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" }
  ]
},
{
  id: 7,
  title: "Episode 07",
  steps: [
    { t:'sec', text:"Groveside Cave" },
    "Turn on Lantern",
    "First room snipe a couple of wolves with bow before dropping down to kill the rest — loot corpse below: <i>Cracked Pot</i>",
    "Kill 2 more wolves further down in the pond, loot 2 more corpses: <i>3x Glowstones</i>, <i>Golden Rune [1]</i>",
    "Northeast tunnel to boss fog, prepare to fight Beastman of Azula",
    "Pop Flask, Enter, Summon Wolves",
    "<i>Flamedrake Talisman</i>",
    "East, find a safe way to drop down to the lake then north to cave entrance to Limgrave Tunnels",
    { t:'sec', text:"Limgrave Tunnels" },
    "Instead of taking elevator down, drop down to the left side, to a small ledge, then drop again to the next ledge below and go inside the tunnel to find: <i>Golden Rune [4]</i>",
    "Drop down to the bottom carefully and you'll find Lost Grace: Limgrave Tunnels",
    "First room can be cleared with all backstabs, drop down after first miner: <i>Smithing Stone [1]</i> (vein), <i>Smithing Stone [1]</i> (vein), <i>Smithing Stone [1]</i> (vein)",
    "Southwest tunnel, loot corpse: <i>Smithing Stone [1]</i>",
    "Northeast tunnel to elevator all the way down",
    "Move up to a room with a wooden cabin, snipe the dog with bow",
    "Inside the cabin: <i>5x Large Glintstone Scrap</i>",
    "Dog + Miner behind cabin, to access a vein: <i>Smithing Stone [1]</i>",
    "Kill miner, loot vein: <i>Smithing Stone [1]</i>",
    "Backtrack to Elevator back up, jump off midway (face southeast)",
    "Defeat miners carefully, I suggest bow pulling one or two for an easier fight: <i>3x Glintstone Scrap</i> (corpse to the right), <i>Smithing Stone [1]</i> (vein)",
    "3rd Elevator, jump down to the left a couple of ledges to get: <i>Golden Rune [1]</i>",
    "Jump down to another ledge below to get: <i>Somber Smithing Stone [1]</i>",
    "To the right, just before the boss double doors: <i>Smithing Stone [1]</i>",
    "Prepare for Boss: Stonedigger Troll",
    "Pop flask before opening double doors, enter, summon Godrick Soldiers Ashes (better for this fight)",
    "Keep your distances, use Unsheathe R2 — could be a bit more challenging than previous bosses so check video to see the strategy in action",
    "<i>Roar Medallion</i>",
    "Exit",
    "Warp back to Limgrave Tunnels",
    "Use all your runes to level, if you're short a few hundred runes, pop some Golden Runes",
    { t:'tip', text:"We're about to take on a dangerous enemy, so don't carry a lot of runes on you" },
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "Mix Wondrous Physick: <i>Greenspill Crystal Tear</i> + <i>Strength-Knot Crystal Tear</i>",
    "Talisman change: <i>Lance Talisman</i>",
    "Hotkey Jellyfish Ashes",
    "Craft 2x Fetid Pots",
    "Get back up and out into Lake Agheel",
    "Defeat Agheel the Dragon (check video for strategy)",
    "<i>Dragon Heart</i>",
    "Loot the Lake area: <i>Ruin Fragments</i> (ruins southwestern part of lake), <i>Ruin Fragments</i> (island northwestern part of lake), <i>Arteria Leaf</i> (altar in the center — throw Fetid Pot at one of the poison eggs to trigger chain reaction)",
    "Southeast of lake, guarded by two giant crabs is a grey scarab, kill it and run southeast: <i>Ash of War: Unsheathe</i>",
    "Further southeast → Site of Grace: Agheel Lake South → Rest and spend runes",
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "West to small camp: <i>Silver of Meat</i>",
    "West to the top of the big ruined arch: <i>Slumbering Egg</i>",
    "Go below the arch and talk to Yura 2x"
  ]
},
{
  id: 8,
  title: "Episode 08",
  steps: [
    "Re-equip Axe Talisman",
    "Re-hotkey Wolf Ashes",
    "Northwest to Dragon-Burnt ruins",
    { t:'warn', text:"Don't open chest behind a door downstairs in the middle of the ruins — it's a trap. Teleports you to a very dangerous place where you will most certainly die." },
    "Clear out the camp carefully (dogs are the main threat) — summon Wolves for an easier time: <i>Stonesword Key</i>, <i>Golden Rune [2]</i>, <i>Twinblade</i> (double jump in closed ruin, stairs down, chest behind door)",
    "Northeast all the way to bridge: <i>Fire Grease</i> (under bridge)",
    "Keep riding until dismount",
    "Invaded by Bloody Finger Nerijus (check video for strategy — best run back towards the bridge and wait for Yura to come help)",
    "<i>Reduvia Dagger</i>",
    "West to cave, rest at Site of Grace: Murkwater Cave",
    "Level up if enough runes (pop some Golden Runes if you're a few hundreds short)",
    { t:'tip', text:"Stats reminder: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    { t:'sec', text:"Murkwater Cave" },
    "Watch out for the chain bell traps on the floor, you'll get swarmed if you walk into them",
    "First Fork go Left: <i>5x Mushrooms</i> (chest at bottom, guarded by 3)",
    "Go back to Fork, take other tunnel to boss area",
    "Get ready for boss fight after opening the chest: <i>Cloth Garb</i>, <i>Cloth Trousers</i>",
    "Bring Patches down to 50% HP, do not finish him off — we need him for his quest line",
    "<i>2x Golden Rune [1]</i>",
    "<i>Gesture: Grovel For Mercy</i>",
    "Talk to Patches",
    "\"Forgive and Forget\"",
    "Warp to Mistwood Outskirts",
    "Northeast to Kenneth Haight for quest reward: <i>Erdtree Dagger</i>",
    "Talk to him again 2x",
    "\"Pledge Service\"",
    "South to Mistwood Ruins, use gesture: Finger Snap",
    "Talk to Blaidd the Half-Wolf 2x",
    "Warp to The First Step",
    "Talk 3 times to Varré, say \"I'll fly straight and true!\"",
    "East/southeast you'll find a hole: <i>Smithing Stone [1]</i>",
    "Further east find location for \"Homing Instinct\" painting: <i>Incantation Scarab</i>",
    "Southeast on top of a rock: <i>Golden Rune [1]</i>",
    "Southeast along the edge until you find Site of Grace: Seaside Ruins → Rest and level up",
    { t:'tip', text:"Stats reminder: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "South find Spiritspring, use it to jump down safely to the beach",
    "West defeat a Gravity Lord (careful, tough enemy — use Unsheathe as much as needed): <i>Ash of War: Gravitas</i>",
    "Northwest to a small cave: <i>Haligdrake Talisman</i>",
    "Don't drop down, this is actually the starting area where we did the tutorial"
  ]
},
{
  id: 9,
  title: "Episode 09",
  steps: [
    "Go back and get out of the cave",
    "South to the beach: <i>3x Lump of Flesh</i>",
    "Go back to spiritspring and jump back up",
    "Southeast along the edge until you find way downwards: <i>Crab Eggs</i> (corpse by cliff's edge)",
    "Kill the demi-humans there until you're out of combat",
    "Warp to Agheel Lake South",
    "South to Forlorn Hound Evergaol",
    "Enter the Evergaol",
    "Touch Gold summon sign — Blaidd the Half-Wolf",
    "Defeat Forlorn Knight Darriwil",
    "<i>Bloodhound's Fang</i>",
    "Talk to Blaidd: <i>Somber Smithing Stone [2]</i>",
    "Talk to Blaidd again",
    "South/Southeast, take Spiritspring down — right next to it: <i>Large Club</i> (guarded by some weak demi-humans), <i>Arteria Leaf</i>",
    "Take spiritspring back up facing northeast",
    "Go around the cliff and then north to use another spiritspring to cross the gulch and land behind a camp with 2 square ruins",
    "Clear the path east to sundial: <i>Starlight Shards</i>",
    "On top of northeast ruins, backstab the mage: <i>Royal House Scroll</i>",
    "Face west and snipe the other mage on opposite ruins",
    "Go down, summon wolves and clear the camp: <i>Great Epée</i> (chest in middle of the camp)",
    "Southwest back on the road then south to guarded bridge",
    "Stay on horse and dash straight for the ballista, then deal with the rest",
    "Loot the bridge: <i>Stonesword Key</i>, <i>3x Smithing Stone</i>",
    "Past the bridge to the right → Site of Grace: Bridge of Sacrifice → Rest and level if enough runes",
    { t:'tip', text:"Stats reminder: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "East by the road find Irina",
    "Talk to her 2x",
    "\"Deliver the letter\"",
    "Warp to The First Step",
    "Northwest to ruins: <i>Ruin Fragments</i>",
    "Northwest to the path to the beach (run past giant): <i>Ruin Fragments</i> (building at bottom of path)",
    "Defeat Giant Octopus (charged attack in the face to stagger): <i>Land Octopus Ovary</i> (corpse by the sea)",
    "Kill another Giant Octopus",
    "Northeast look for an Invisible Scarab — white steps on the sand — easiest method is on horseback holding R2 or L2 (check video to see the timing): <i>Ash of War: Stamp (Sweep)</i>",
    "Further northwest by campfire guarded by barbarian: <i>Strip of White Flesh</i>",
    "South along the beach to Coastal Cave → Site of Grace: Coastal Cave → Rest",
    "Talk to Boc the Seamster once",
    "Get out of cave and go further southeast to Nomadic Merchant, purchase: <i>Armorer's Cookbook [2]</i>, <i>Neutralizing Boluses</i>",
    { t:'tip', text:"We can craft Neutralizing Boluses now but better have some extras since one of the components (Great Dragonfly Head) is annoying to get" },
    "Further Southeast at the end of the beach: <i>Gold-Picked Owl Foot</i>",
    "Warp back to Coastal Cave"
  ]
},
{
  id: 10,
  title: "Episode 10",
  steps: [
    { t:'sec', text:"Coastal Cave" },
    "Use Lantern",
    "First tunnel to the right, kill a bunch of demi-humans, loot corpse: <i>Land Octopus Ovary</i>",
    "Before dropping down, touch gold summon sign to summon Old Knight Istvan",
    "Prepare for boss fight: 2x Demi-human Chief",
    "Pop flask, drop down, summon Wolves",
    "Focus down one enemy quickly — don't bother with the adds, they keep respawning",
    "<i>Tailoring Tools</i>",
    "<i>Sewing Needle</i>",
    "DON'T take the teleport back up, instead take the tunnel southwest behind it: <i>Smoldering Butterfly</i>",
    "Exit on the other side to Dragon Island",
    "Southwest → Site of Grace: Church of Dragon Communion",
    "Pray at the Altar and purchase any dragon incantation",
    "West of the church find corpse: <i>4x Great Dragonfly Head</i>",
    "Back to the church, climb up the ruin just southwest behind the church, on top is a corpse: <i>Exalted Flesh</i>",
    "South drop down and further south find and kill Scarab: <i>Somber Smithing Stone [1]</i>",
    "East along the coast line find a corpse near the edge: <i>Smithing Stone [2]</i>",
    "Warp back to Coastal Cave",
    "Talk to Boc",
    "Give him the Sewing Needle",
    "Talk to Boc again",
    "Warp to Agheel Lake North",
    "Wait until Nightfall",
    "Follow road east until bridge",
    "Defeat Night's Cavalry (check video for strategy): <i>Art of War: Repeated Thrust</i>",
    "Southeast past the bridge: <i>Somber Smithing Stone [1]</i> (dead guy on a chair)",
    "East on a cliff overlooking the road: <i>Gold-Pickled Fowl Foot</i>",
    "Further south down the path, clear Caravan: <i>Great Axe</i> (back of cart)",
    "Further southeast to waypoint ruins, stay on horse to kill giant flower: <i>Miranda Powder</i>, <i>5x Poisonbloom</i>, <i>Immunizing Cured Meat</i>",
    "Climb broken wall to reach corpse: <i>4x Trina's Lily</i>",
    "Southwest stairs down that lead you to a boss fight: Mad Pumpkin Head",
    "Enter, summon wolves, keep shield up and let wolves get aggro",
    "Use Unsheathe R2 to strike from behind — don't hit the head, it's heavily armored",
    "Rest at Site of Grace: Waypoint Ruins Cellar",
    "Level up if you've got enough runes",
    "Open door",
    "Talk to Sorceress Sellen",
    "\"I want to learn sorcery\"",
    "\"I still want to learn\"",
    { t:'tip', text:"Don't give her any scrolls, we'll give them to a more convenient teacher later" },
    "If you're a spellcaster, purchase any spell you like",
    "<i>Gesture: Nod in Thought</i>",
    "Warp to Artist's Shack",
    "Southwest to find a Scarab (explodes on death): <i>Somber Smithing Stone [1]</i>",
    "Northwest, cross the ruins over the ravine and find Site of Grace: Murkwater Coast"
  ]
},
{
  id: 11,
  title: "Episode 11",
  steps: [
    "From Site of Grace: Murkwater Coast",
    "Southwest to Barbarian Camp in between two ruins (3-4 Barbarians + 4 Wolves)",
    "Summon Wolves to help you clear this camp",
    { t:'tip', text:"Check video for combat tips: how to deal with aggressive enemies using big weapons, how to deal with mounted enemies while on foot" },
    "Clear the camp and loot corpse: <i>Armorer's Cookbook [1]</i>",
    "Northwest/north past ruin and spiritspring to an item on a small hill: <i>Smithing Stone [1]</i>",
    "Southeast jump off cliff to an area with a wolf pack — kill it then look for corpse by a rock: <i>Golden Rune [2]</i>",
    "Northeast to find a statue on top of the cliff",
    "Examine statue to see the way to next dungeon at bottom of ravine",
    "Use tombstones to drop down safely to the bottom and find the catacombs entrance",
    "Site of Grace: Murkwater Catacombs → Rest",
    "Level up (pop a few Golden Runes if you're a few hundreds short)",
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "Mix Wondrous Physick: <i>Spiked Cracked Tear</i> + <i>Strength-Knot Crystal Tear</i>",
    { t:'sec', text:"Murkwater Catacombs" },
    "First room, 3x Imp Ambush from the ceiling: <i>Grave Glovewort [1]</i>, <i>Grave Glovewort [1]</i>",
    "Southwest corridor, floor tile trap — check video to see how to use it to your advantage to kill the 2 imps by the lever",
    "Imp ambush left in Lever room: <i>5x Root Resin</i>",
    "Pull lever",
    "Backtrack and take southwest tunnel",
    "Floor tile trap again + Imp ambush above doorway: <i>Ghost Glovewort [1]</i>",
    "Prepare for boss Grave Warden Duelist",
    "<i>Banished Knight Engvall</i>",
    "Warp to Saintsbridge → Rest and Level",
    "East, jump off the bridge to the right on the Spiritspring to get down to the river",
    "Head North until you reach cave on the left side of the ravine",
    "Enter the cave to find Site of Grace: Highroad Cave",
    { t:'sec', text:"Highroad Cave" },
    "Drop down the first hole using the midway platforms",
    "2nd room with a hole, kill 3 wolves",
    "East tunnel, kill 2 more wolves, loot corpse: <i>Golden Rune [1]</i>",
    "Back to room, check the other nook for Cave Moss",
    "Get down the hole, west first for some Cave Moss",
    "Go the other way until campfire, take a left (Northwest tunnel): <i>3x Arteria Leaf</i> (wolf ambush behind)",
    "Drop down to kill Alpha Wolf and then 3 more wolves: <i>2x Fire Grease</i> (corpse sticking out of bushes)",
    "North tunnel to large cave area",
    "North along the wall, drop down, kill 2 bats",
    "Turn around and south kill another bat guarding a corpse: <i>3x Smithing Stone [1]</i>",
    "North, drop down on waterfall, 2x Gargoyle Ambush: <i>Smithing Stone [2]</i> (cave where ambush came from), <i>Golden Rune [4]</i> (behind waterfall in the same small cave, guarded by 2x Octopus)",
    "Go back and drop down southeast at the foot of waterfall",
    "Jump over to platform, walk up the pillar and drop down to kill 2x Bats, followed by 2x Bats coming from each side",
    "Loot corpse: <i>Shamshir</i>",
    "Exit platform Southeast, fight giant Octopus (hanging from ceiling) at end of tunnel",
    "<i>Furlcalling Finger Remedy</i> (at other end of tunnel past Octopus)",
    "Turn left and jump down into next waterfall, to boss area: Guardian Golem",
    "Before entering: Flask of Physick",
    "Enter: summon Wolves + FP Flask",
    "Lock-on the legs and use Charged Attacks to bring it down",
    "Critical Strike the belly (tip: you can land a fully charged attack while it's down, before the critical strike)",
    "<i>Blue Dancer Charm</i>",
    "Warp back to Saintsbridge → Level up",
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "Ash of War: <i>Uchigatana +4</i> → Sacred Blade → Sacred",
    "Wait until morning",
    "Ride east along the trail and find a knight in gold and silver armor by the side of the road",
    "Talk to D",
    "Southeast until Site of Grace: Summonwater Village Outskirts",
    "Prepare for Boss: Tibia Mariner (check video for strategy)",
    "As soon as you see it, pop Flask of Physick and summon wolves",
    "Use Sacred Blade to kill the undeads he summons",
    "If he teleports away, get back on Torrent and chase after him",
    "<i>Deathroot</i>",
    "<i>Skeletal Militiaman Ashes</i>",
    "Northwest corner of Summonwater Village: <i>Smithing Stone [1]</i>, <i>3x Mushroom</i> (middle of ruins)",
    "East to ruins up above, find a small tower: <i>Golden Rune [4]</i>",
    "South to find stairs down inside ruins, use Stonesword Key: <i>Green Turtle Talisman</i>",
    "Equip it",
    "South you'll find a Crimson Scarab you can kill to replenish flasks",
    "Southeast drop down to graveyard: <i>Golden Rune [2]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [5]</i>",
    "East and take Spiritspring up north to Tunnel Entrance, find Site of Grace: Rear Gael Tunnel Entrance"
  ]
},
{
  id: 12,
  title: "Episode 12",
  steps: [
    "From Site of Grace: Rear Gael Tunnel Entrance",
    "Ash of War: <i>Uchigatana +4</i> → Unsheathe → Standard",
    "Talk 2x to Alexander the Pot Warrior",
    "<i>Smithing Stone [4]</i> (vein behind pot warrior)",
    "Get out of the cave and warp to Bridge of Sacrifice",
    "Southeast until area with broken cart: <i>Morning Star</i> (back of big chariot), <i>Strip of White Flesh</i> (corpse guarded by 3 dogs), <i>Golden Rune [2]</i> (corpse), <i>Smithing Stone [2]</i> (near cart), <i>Ruin Fragments</i>",
    "South to find Grey Scarab, kill it: <i>Ash of War: Mighty Shot</i>",
    "Southwest out of the gulch and then southeast to find Site of Grace: Castle Morne Rampart",
    "Next to the grace is a merchant, purchase: <i>Cracked Pot</i> (600 Runes), <i>Stonesword Key</i> (2000 Runes), <i>Smithing Stone [2]</i> (400 Runes)",
    { t:'tip', text:"Optional: Crimson Amber Medallion (1500 Runes) — we'll get a better version of this medallion, but if for completion's sake you want every talisman, buy this one. My advice is to save your runes for now and purchase it later." },
    { t:'tip', text:"Kill the merchant. Upon death they drop a Bell Bearing you can give to the Twin Maiden Husks at Roundtable Hold to access the dead merchant's inventory — very convenient to access everything in one place later. This is optional — if for roleplay reasons you don't want to kill merchants, that's fine." },
    "<i>Nomadic Merchant's Bell Bearing [4]</i> (if you kill this merchant)",
    "Rest until nightfall to spawn a Night's Cavalry Boss in this area",
    "Defeating it on horseback is easier: <i>Ash of War: Barricade Shield</i>, <i>Nightrider Flail</i>",
    "Rest at the grace and pass time until morning",
    "Ride South to get the Weeping Peninsula Map Fragment — watch out for the golem shooting giant arrows at you, keep moving",
    "Southwest to small Erdtree: <i>Golden Seed</i>",
    "Go back north until out of range of the golem archer",
    "Follow the trail going up west until you find a house with a campfire in front: <i>Yellow Ember</i>",
    "Back on the trail, northwest all the way to the cliff's edge — then a few steps north to find a campfire — kill 2 Yellow Eyed fanatics, loot corpse: <i>Golden Rune [2]</i>",
    "Southeast to Callu Baptismal Church",
    "Summon Wolves and clear the area of all rats / frenzied flame fanatics",
    "Inside the church loot: <i>The Flame of Frenzy</i>, <i>Sacred Tear</i>",
    "Northeast to Ailing Village — at the northernmost house inside: <i>Flame Crest Wooden Shield</i>",
    "Northeast to Site of Grace: Ailing Village Outskirts",
    "Spend all runes, we're about to do something risky",
    "Southwest to cliff's edge overlooking gulch with lightning storm going on and a Scarab below",
    "Drop down using the steles",
    "Ignore bats, defeat Scarab even if it gets you killed: <i>Lightning</i> (incantation)",
    "Beat the bats if you can, or die — doesn't matter",
    "Warp back to Lost Grace: Castle Morne Rampart",
    "East to take Spiritspring, face south and aim for the top of the tower: <i>Great Turtle Shell</i>, <i>2x Warming Stone</i>",
    "Warp to Roundtable Hold",
    { t:'tip', text:"Hotkey to quickly warp — PS: Map > Triangle > Square > Cross / Xbox: Map > Y > X > A" },
    "You'll need 918 Runes for upgrades now — pop some Golden Runes if needed",
    "Go to Smithing Master Hewg",
    "About Roderika",
    "Upgrade <i>Uchigatana +5</i>",
    "Talk to Roderika",
    "Spirit Tuning: <i>Jellyfish Ashes +1</i>",
    "Go back to the roundtable, D should be there",
    "Talk to D",
    "\"Show Deathroot\"",
    "\"Accept introduction\"",
    "North hallway to Sir Gideon Ofnir, the All-Knowing",
    "\"What do you mean, a house guest?\"",
    "Talk to him again"
  ]
},
{
  id: 13,
  title: "Episode 13",
  steps: [
    "Warp to Stormhill Shack",
    "Check where Roderika was when we first met her: <i>Golden Seed</i>",
    "Go to Stormveil Castle, zig zag to avoid ballista shots — get behind it and deal with guards",
    "Further inside to Lost Grace: Castleward Tunnel → Rest",
    "Upgrade Flasks: Increase Flask Charges (7) + Increase Amount Replenished (+3)",
    "Hotkey Spirit Jellyfish Ashes +1 (better than wolves for this fight)",
    "Further up, touch Gold Summon Sign to Summon Sorcerer Rogier",
    "Pop Flask of Physick",
    "Enter, summon Jellyfish",
    "Defeat Margit the Fell",
    "<i>Talisman Pouch</i>",
    "Lost Grace: Margit, the Fell Omen → Rest and spend runes",
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20" },
    "Equip Axe Talisman in 2nd Talisman slot",
    "Move up to Lost Grace: Stormveil Main Gate",
    "Northeast stairs down: <i>Furlcalling Fingers Remedy</i>",
    "Go back and enter left door and talk to Gatekeeper Gostoc",
    "\"Very well\"",
    "<i>Golden Rune [1]</i> (ledge to the left)",
    "<i>3x Ruin Fragment</i> (climb up ruins)",
    "<i>Smithing Stone [2]</i> (keep climbing ruined walls)",
    "Face south and drop down — work your way down through a couple of birds",
    { t:'tip', text:"These birds can be dangerous — you can one shot them with a Mighty Shot Fire Arrow to thin their numbers and fight them one by one. Keep your shield up when they swoop down on you." },
    "Once you're all the way down, follow ledge north until corpse: <i>10x Bolt</i>",
    "Southwest work your way back up, careful with birds: <i>Smithing Stone [3]</i> (corpse guarded by 1 Bird + 2 more birds ambush)",
    "Follow ledge to your left until Lost Grace: Stormveil Cliffside",
    "Risky upgrade mission time — we're going to grab some upgrades in a dangerous high level area (check video to see exactly where to go to lower your chances of dying)",
    "Warp to Seaside Ruins",
    "North to Dragon-Burnt Ruins",
    "Go downstairs, through room with rats, open door and take chest trap teleport",
    { t:'sec', text:"Sellia Crystal Tunnel" },
    "Sneak out and down to find Site of Grace: Sellia Crystal Tunnel",
    "Exit tunnel, hug wall to your right until you find a gulch heading North — go to the end of it: <i>Somber Smithing Stone [5]</i>",
    "Exit Gulch, go Southwest to Street of Sages Ruins: <i>Rock Sling</i> (first ruined building, find stairs down and open door)",
    "Exit cellar, south to elevated building: <i>Traveler's Armor Set</i>, <i>Perfumer's Traveling Garb</i>, <i>Perfume Bottle</i>",
    "Southwest to guard tower: <i>Meteorite Staff</i>",
    "South then Southwest to Lost Grace: Aeonia Swamp Shore",
    "Northwest to Lost Grace: Astray from Caelid Highway North",
    "Northwest near ravine: <i>Somber Smithing Stone [4]</i> (dead guy in chair overlooking the camp with pumpkin head — you can climb from there with double jump or go the other way around to drop down)",
    "Warp to 3rd Church of Marika",
    "North to Waygate to Bestial Sanctum → Open door",
    "Lost Grace: Bestial Sanctum",
    "Talk to Gurranq, give him 2x Deathroot",
    "<i>Clawmark Seal</i>",
    "<i>Beast Eye</i>",
    "<i>Bestial Sling</i>",
    "Ride southeast towards Farum Greatbridge, on the way: <i>Golden Seed</i>",
    "Keep going southeast along the path until Site of Grace: Farum Greatbridge",
    { t:'tip', text:"This is a really good Rune Farming Spot if you're behind or want to level ahead (check video for one clear)" },
    "In any case, do one loop of this farming route to grab: <i>Somber Smithing Stone [9]</i> (west of grace), <i>Starlight Shard</i> (northeast of grace on upper plateau)"
  ]
},
{
  id: 14,
  title: "Episode 14",
  steps: [
    "From Farum Greatbridge",
    "Ride south past dragon, past Minor Erdtree, Spiritspring up above, all the way south to Site of Grace: Fort Faroth",
    "Mix Wondrous Physick: <i>Green Spilled Tear</i> + <i>Strength-Knot Crystal Tear</i>",
    "Hotkey: <i>Gold Pickled Fowl Foot</i> + Lone Wolf Ashes",
    "Beat up on the dragon's tail until he's almost dead",
    "Use <i>Gold Pickled Fowl Foot</i> before you finish the dragon to get extra runes",
    "<i>5x Dragon Heart</i>",
    "Spend Runes immediately",
    { t:'tip', text:"Stats goals: VIG 20 → STR 18 → END 15 → DEX 17 → VIG 25 → END 20 → VIG 35 → DEX 20 → END 25 → DEX 35 → STR 35" },
    "Make sure you've got no runes left on you, high chance to die on this next step",
    "Enter Fort Faroth (check video on how to get the items below): <i>Dectus Medallion (Right)</i>, <i>Golden Rune [12]</i>, <i>Radagon's Soreseal</i>",
    "Die or survive the rats",
    "Warp back to Fort Faroth",
    "Equip <i>Radagon's Soreseal</i>",
    { t:'tip', text:"Trophy progression: Legendary Talismans 1/8" },
    "Northeast, take spiritspring down to Minor Erdtree, keep going northeast along the eastern cliff edge until graveyard: <i>Golden Rune [3]</i>, <i>Golden Rune [6]</i>, <i>Golden Rune [8]</i>, <i>Golden Rune [1]</i>",
    "Northeast spiritspring down to Site of Grace: Lenne's Rise",
    "Check video for next part — we can defeat a very high level Night's Cavalry using a trick",
    "Wait until Nightfall",
    "Drag Night's Cavalry to your side of the bridge, then jump on the outer ledge of the bridge to have him chase you and fall to his death",
    "<i>Ash of War: Bloodhound's Step</i>",
    "Warp to Roundtable Hold",
    "Talk to D",
    "\"About D\"",
    "Go to Smithing Master Hewg: Upgrade <i>Bloodhound's Fang to +5</i>",
    "Go to Roderika: Upgrade <i>Skeletal Militiaman Ashes +1</i>",
    "Gear changes: Equip <i>Bloodhound's Fang</i>, Hotkey Banished Knight Engvall",
    { t:'tip', text:"Bloodhound's Fang is an amazing weapon and could carry you until the end of the game. Radagon's Soreseal gives +20 Levels worth of stats. Enemies will die quickly from now on." },
    { t:'sec', text:"Weeping Peninsula" },
    "Warp to Castle Morne Rampart",
    "Level up (you should have some runes left after upgrading)",
    "East, take spiritspring up",
    "Solve Riddle at Oridys's Rise — read the Riddle: kill 3 Turtles in the area",
    "1st Turtle hidden in the bushes left of the stair",
    "2nd Turtle a few steps back on the trail",
    "3rd Turtle invisible in the pond",
    "<i>Arteria Leaf</i> (by the pond)",
    "Go to the top of the tower: <i>Memory Stone</i>",
    "East to Sundial: <i>Starlight Shards</i>",
    "North/Northwest to Lost Grace: Besides the Crater-Pocked Glade",
    "North till cliff's edge: <i>Stonesword Key</i> (dead guy in chair)",
    "Southeast to find path going down catacombs entrance",
    "Enter and find Site of Grace: Impaler's Catacombs"
  ]
},
{
  id: 15,
  title: "Episode 15",
  steps: [
    { t:'sec', text:"Impaler's Catacombs" },
    "<i>Grave Violet</i> (down first set of stairs)",
    "Imp ambushes",
    "<i>Grave Glovewort [1]</i> (2nd room with 3 imps)",
    "Go straight and left: <i>Grave Glovewort [2]</i> (imp ambush)",
    "Next room floor is a trap — first, jump off to alcove to the left to grab: <i>Grave Violet</i>",
    "To get back down, trigger trap, jump back to alcove, then as the floor is going down get back to the door",
    "This time trigger floor and drop under it: <i>Grave Violet</i>, <i>Ghost Glovewort [2]</i>",
    "Next room enemies respawn endlessly, so just grab loots and move on: <i>Prattling Pate \"Please Help\"</i>, <i>Grave Glovewort [2]</i>, <i>Grave Glovewort [1]</i>, <i>3x Root Resin</i> (alcove to the left), <i>Grave Glovewort [1]</i>",
    "Ladder up",
    "Pull Lever",
    "<i>Grave Glovewort [2]</i> (Imp ambush)",
    "Jump off through window",
    "Go rest if needed",
    "Take opened door to boss area",
    "PREPARE FOR BOSS: Erdtree Burial Watchdog",
    "Hotkey Skeletal Militiaman",
    "Pop Flask of Physick",
    "Enter: summon Militiaman, kill the 4 Imps first, use our new Ash of War combo: L2 / R2",
    "<i>Demi-Human Ashes</i>",
    "<i>2x Root Resin</i>",
    "Warp to Lost Grace: Besides the Crater-Pocked Glade",
    "North/Northwest drop down on ruins bridge: <i>3x Sanctuary Stone</i>",
    "West to other cliff, go to watch tower and kill guards (one is up rampart tossing fire pots, careful, take him out — can climb up from the right side)",
    "Climb to the top and take out ballista handler, open chest: <i>Hand Ballista</i>, <i>5x Ballista Bolt</i>",
    "Go back down: <i>3x Golden Rune [1]</i> (in front of tower)",
    "Further southeast: <i>3x Golden Rune [1]</i>",
    "Bottom of path on a small plateau, find Site of Grace: South of the Lookout Tower",
    "Southeast by the cliff's edge next to a stake guarded by dogs: <i>5x Rainbow Stone</i>",
    "Northwest to ruins: <i>3x Ruin Fragment</i>",
    "Northeast small camp with a corpse guarded by 2 Demi-humans: <i>Rainbow Stone</i>",
    "Further northeast find path going down to Earthbore Cave",
    "Site of Grace: Earthbore Cave → Activate Lantern",
    "<i>3x Pickled Turtle Neck</i> (chest, watch out trap in front — ground is crackled, go around it)",
    "Tunnel down until couple of rats: <i>Golden Rune [1]</i>",
    "Room with big rat, proceed to next tunnel: <i>5x Glowstone</i>, <i>8x Kukri</i>",
    "Drop down the hole carefully, aim for midway platform",
    "PREPARE FOR BOSS: Runebear",
    "Flask of Physicks",
    "Summon Militiaman",
    "Engage: L2/R2 combos for an easy win",
    "<i>Spelldrake Talisman</i>",
    "<i>5x Smoldering Butterfly</i>",
    "<i>Trina's Lily</i>",
    "Exit",
    "Get back up the path then west to Demi-Human Forest Ruins",
    "Beat miniboss Demi-Human Queen (get the jump on her and kill her fast, all her minions will then be stunned in fear): <i>Demi-Human Queen's Staff</i>, <i>Crystal Burst</i>, <i>Arteria Leaf</i>",
    "North to cliff edge: <i>Faith-Knot Crystal Tear</i>",
    "Southern part of the ruins: <i>Shield of the Guilty</i> (double jump above walls to find stairs down with chest)",
    "Southeast until giant flower, loot corpse next to it and keep going: <i>Golden Rune [2]</i>",
    "Further southwest under the bridge, until you find tunnel entrance",
    "Instead of taking elevator, drop down left ledge by the elevator, then drop down again: <i>Smithing Stone [1]</i> (vein at end of tunnel)",
    "Drop down again a couple of ledges on your left hand side until you reach the bottom",
    "Site of Grace: Morne Tunnel",
    { t:'sec', text:"Morne Tunnel" },
    "Cross planks, beat enemy, go left and jump across next platform, climb ladder: <i>Smithing Stone [1]</i>",
    "Go back and take south tunnel, beat 3 enemies: <i>Golden Rune [2]</i>",
    "Face NE, kill miner: <i>Smithing Stone [1]</i>",
    "Go down, kill miner: <i>Smithing Stone [1]</i>",
    "South to a shack: <i>Golden Rune [4]</i>, <i>Exalted Flesh</i> (chest), <i>Somber Smithing Stone [1]</i> (behind shack), <i>2x Large Glintstone Scrap</i> (alcove northwest of shack)",
    "Go back, beat 2 miners under the wooden platforms: <i>Smithing Stone [1]</i> (vein), <i>Stanching Boluses</i>",
    "Keep going west you'll end up in the room below the planks we walked across — clear the room then loot everything: <i>2x Arteria Leaf</i>, <i>Smithing Stone [1]</i>, <i>Smithing Stone [1]</i>, <i>Somber Smithing Stone [1]</i>, <i>Smithing Stone [1]</i>, <i>Smithing Stone [1]</i>",
    "West tunnel: <i>Soft Cotton</i>",
    "Northeast tunnel towards boss area: <i>Somber Smithing Stone [1]</i> (to the right before boss door)",
    "Defeat boss: Scaly Misbegotten",
    "<i>Rusted Anchor</i>",
    "Exit",
    "North to spiritspring on top of the cliff",
    "Northwest all the way to Site of Grace: Church of Pilgrimage"
  ]
},
{
  id: 16,
  title: "Episode 16",
  steps: [
    "From Church of Pilgrimage",
    "Inside the church: <i>Sacred Tear</i>",
    "Rest",
    "Level up",
    { t:'tip', text:"Stats goals: VIG 35 → END 25 → DEX 35 → STR 35" },
    "Flasks: Increase amount replenished (+4)",
    "Talk to Melina",
    "Graveyard just west of church: <i>2x Blood Grease</i>, <i>Gilded Iron Shield</i>",
    "Ride south to the Minor Erdtree, prepare for boss: Erdtree Avatar (check video for detailed strategy)",
    "Before engaging: summon Skeletal Militiaman + Flask of Physick",
    "Engage: stay on horseback, circle around, wait for missed attacks, 1 or 2 hits only",
    "<i>Opaline Bubbletear</i>",
    "<i>Crimsonburst Crystal Tear</i>",
    "Hotkey Neutralizing Boluses",
    "South to cliff's edge where you'll hear singing — clear the bats before dropping down, kill the Singing Bat: <i>Golden Rune [6]</i>, <i>Sliver of Meat</i> (corpse)",
    "West/Northwest to ruins: <i>3x Sanctuary Stone</i>",
    "South drop down, go to pond, beat octopus and kill the invisible Scarab to get some flasks back",
    "Southwest to 3 stakes, beat enemies: <i>3x Dragonfly Head</i>",
    "West a long way towards the beach to Site of Grace: Isolated Merchant's Shack",
    "Purchase from merchant: <i>3x Stonesword Key</i> (6000 R)",
    { t:'tip', text:"Optional: kill merchant for Isolated Merchant's Bell Bearing [1]" },
    "Spend all runes, something risky is coming up",
    "Southeast to graveyard: <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>Golden Rune [3]</i>",
    "North then southeast up the cliff to the watch tower — ignore enemies, climb 3 ladders and take out ballista guy",
    "Then open chest, trap teleport to Leyndell",
    "Southwest to Site of Grace: Divine Bridge",
    "Run past colossus and to the right: <i>Blessed Dew Talisman</i> (chest)",
    "Die or run back to Lost Grace if you can",
    "Warp back to Isolated Merchant's Shack",
    "Northwest to beach, corpse by the water: <i>Golden Rune [5]</i>",
    "East/northeast next to a tree with the zombie horde: <i>Golden Rune [1]</i>",
    "East/southeast to Witchbane Ruins — stay on horse to avoid poison buildup",
    "Clear the place, find corpse in northwest part of ruins: <i>Dragonfly Head</i>",
    "Find stairs down: <i>Ambush Shard</i>",
    "Don't attack the witch down there — we'll be back here later for a quest",
    "Northwest then Northeast up the cliff to Fourth Church of Marika: <i>Sacred Tear</i>",
    "Site of Grace: Fourth Church of Marika",
    "Flasks: Increase Amount Replenished (+5)",
    "Northeast to Weeping Evergaol",
    "Use Stonesword Key",
    "Enter evergaol, drink Flask of Physick, engage",
    "Use Bloodhound's Finesse to make quick work of Ancient Hero of Zamor (watch out for frostbite buildup though)",
    "<i>Radagon's Scarseal</i>",
    "South, drop down a ledge below to find a cave entrance",
    "Site of Grace: Tombsward Cave",
    { t:'sec', text:"Tombsward Cave" },
    "Down the first tunnel, reach the poison swamp room, kill 2 mushroom men: <i>Golden Rune [2]</i>",
    "Clear the rest of the room",
    { t:'tip', text:"Never roll into poison or rot, it will stick to your armor and keep building up until you're poisoned. If poisoned, craft Neutralizing Boluses." },
    "Loot corpse: <i>Furlcalling Finger Remedy</i>",
    "North, kill rat pack at the end of tunnel: <i>Immunizing White Cured Meat</i>, <i>Nomadic Warrior's Cookbook [8]</i>",
    "Take other path to the right, kill 3 flowers: <i>Arteria's Leaf</i>",
    "Drop down, to your right: <i>6x Poisonbone Dart</i>",
    "Tunnel south to boss room",
    "Miranda the Blighted Bloom (just kill her fast)",
    "<i>Viridian Amber Medallion</i>",
    "Exit",
    "East/southeast to Site of Grace: Tombsward"
  ]
},
{
  id: 17,
  title: "Episode 17",
  steps: [
    "From Site of Grace: Tombsward",
    "West, kill all 9 ghostly knights, they can drop Brass Shield (rare drop) and we'll want that shield at some point",
    { t:'tip', text:"Don't bother farming it for now because we'll kill many other enemies who can drop it while progressing through the story" },
    "Stop the Walking Mausoleum by beating the white skulls off its feet",
    "Open map and place a marker at this location to find the Mausoleum easily later when we'll come back to duplicate a Remembrance",
    "Northeast to ruins: <i>3x Ruin Fragment</i>, <i>3x Tarnished Golden Sunflower</i>",
    "Northwest to other ruins, kill grey scarab on top of it: <i>Divine Fortification</i>",
    "Northeast to Tombsward Ruins: <i>Beast Liver</i>, <i>5x Trina's Lily</i>",
    "Find stairs down, clear 2 enemies, open door: <i>Winged Scythe</i> (chest)",
    "East/northeast back on the high cliff, then south follow path on the right side to Tombsward Catacombs",
    "Site of Grace: Tombsward Catacombs",
    { t:'sec', text:"Tombsward Catacombs" },
    "Equip Uchigatana +5 → Ash of War: Sacred Blade (Affinity: Sacred)",
    "Use Stonesword Key: <i>Nomadic Warrior's Cookbook [9]</i>",
    "First room, kill 2x Skeletons: <i>Grave Glovewort [1]</i>, <i>Grave Glovewort [2]</i>",
    "2nd room with fog, kill 4 Skeletons: <i>Grave Glovewort [1]</i> (to the right), <i>Ghost Glovewort [1]</i> (under the archways)",
    "East hallway: <i>Grave Glovewort [1]</i>",
    "Fire Trap — deactivate with a Bone Arrow (craft some if you're out, don't waste Fire Arrows on this)",
    "Loot corpse in the hallway towards Fire Trap: <i>5x Human Bone Shard</i>",
    "To the right of fire trap: <i>Grave Violet</i>",
    "East room, 4x Skeleton Ambush: <i>Grave Glovewort [2]</i>, <i>Prattling Pate \"Thank You\"</i>",
    "Jump on Fire Trap while bumping into it to go up: <i>Golden Rune [2]</i>",
    "Next room: <i>Grave Violet</i>",
    "Next room: <i>Grave Glovewort [2]</i>",
    "North hallway: Pull Lever, <i>Grave Violet</i>",
    "Drop down — go back to the boss door room",
    "If needed go back to rest at the grace",
    "Go back to opened door and move to boss area",
    "Re-equip Bloodhound's Fang",
    "Prepare for Boss: Cemetery Shade",
    "Before entering: Flask of Physick",
    "Enter: summon Skeleton Militiaman, let them get aggro, L2 > R2 Combo for a quick win",
    "<i>Lhutel The Headless</i>",
    { t:'tip', text:"Trophy Progression: Legendary Ashen Remains 1/6" },
    "<i>3x Root Resin</i>",
    "Exit",
    "Make your way back up to the top of the hill, then south along your right-hand side edge — drop down to a platform with 3x Erdleaf Flower, drop down again: <i>Eclipse Crest Heater Shield</i>",
    { t:'tip', text:"Equip it if you like this fashion better — it is very similar to our current shield but has different element resistances and already the \"No Skill\" Ash of War equipped." },
    "Warp to Castle Morne Rampart",
    "First, get rid of the Golem archer",
    "Southeast to the beach, guarded by jellyfish (just run past and loot): <i>Somber Smithing Stone [2]</i>, <i>Arteria Leaf</i>",
    "Northwest ruins: <i>3x Sanctuary Stone</i>",
    "East swamp, don't bother killing the enemies — make a lap around the pool to loot the Poisonblooms, then climb up on top of the highest rock: <i>Golden Rune [4]</i>",
    "Northeast to higher plateau then Northwest to find a grey scarab — this one teleports away when you get close so shoot it with a Mighty Shot + Fire Arrow to make sure it doesn't escape: <i>Poison Mist</i>",
    "West/Southwest all the way to the beach, corpse in front of crucifix guarded by dogs: <i>Golden Rune [1]</i>",
    "Southeast/East to Castle Morne, rest at Site of Grace: Castle Morne Lift",
    "LEVEL UP",
    { t:'tip', text:"Stats goals: VIG 35 → END 25 → DEX 35 → STR 35" }
  ]
},
{
  id: 18,
  title: "Episode 18",
  steps: [
    "From Castle Morne Lift",
    { t:'sec', text:"Castle Morne" },
    "Take lift up, reach courtyard, take stairs southeast: <i>Smithing Stone [2]</i>",
    "Ignore big pile of corpses for now, hug left wall, kill Pumpkin Head: <i>Sanctuary Stone</i>",
    "South to a corpse: <i>Smithing Stone [1]</i>",
    "Now go back and clear the demi-humans on the pile of corpses: <i>2x Fire Grease</i>",
    "Behind the pile you'll find a way to the armory: <i>Claymore</i> (chest)",
    "Through the armory, clear the demi-humans and humans fighting",
    "Ladder up to northwestern ramparts, clear big fight going on: <i>Furlcalling Finger Remedy</i> (corpse south corner), <i>Steel-Wire Torch</i> (all the way northeast)",
    "Southwest another ladder up",
    "Move up then drop down southeast, take out 4 enemies across the bridge",
    "<i>Golden Rune [2]</i> (corpse on bridge's side)",
    "After bridge go right, down ladder, northwest at the end of ramparts 1 ambush behind crate and 1 more facing the wall: <i>2x Smithing Stone [2]</i>",
    "Go back up, face northeast, destroy crates to reveal ladder, go down",
    "Northeast, clear enemies fighting each other, loot corpse in the middle: <i>Golden Rune [2]</i>",
    "Up the tower, talk to Edgar: <i>Sacrificial Twig</i>",
    "Deliver Irina's Letter",
    "Talk to him again",
    "Go back all the way Southwest, jump over ramparts to the left using the rubbles as stepping stone",
    "Site of Grace: Behind the Castle → Rest",
    "Drop down a couple of rock platforms, then drop down southwest breach in the wall onto Scaffoldings: <i>Stonesword Key</i>",
    "Drop down northwest, kill the cowering demi-humans",
    "Holding cell to the right with ghost inside, Ambush blob on the ceiling: <i>Pickled Turtle Neck</i>",
    "Northwest climb on top of tower, open chest: <i>Twinblade Talisman</i>",
    "Go back to bridge, drop down on roof below, drop down again: <i>3x Tarnished Golden Sunflower</i>",
    "Crimson Scarab if you need to refill flasks",
    "Southeast jump down to next platform and keep going",
    "Drop down on beam: <i>Smithing Stone [2]</i>",
    "Drop down 2nd beam, ambush by 4 rats below: <i>Whip</i>",
    "Get out and circle left: Site of Grace: Beside the Rampart Gaol → Rest",
    "Southwest cross Bridge, 2 enemies: <i>8x Throwing Daggers</i>",
    "Ladder down, northeast across shallow water, beat Giant Crab ambush: <i>15x Fire Arrow</i> (hidden nook past giant crab)",
    "Go around building we came down from, hug wall and find corpse: <i>1x Somber Smithing Stone</i>",
    "Touch Gold Summon Sign in front of boss gate to summon Castellan Edgar",
    "Prepare for boss: Leonine Misbegotten",
    "Before entering: Flask of Physick",
    "Enter: summon Skeletal Militiaman, let Edgar get the aggro, L2 > R2 Combos",
    "<i>Grafted Blade Greatsword</i>",
    { t:'tip', text:"Trophy progression: Legendary Armaments Achievement: 1/9" },
    "Site of Grace: Morne Moangrave"
  ]
},
{
  id: 19,
  title: "Episode 19",
  steps: [
    "Warp back to Castle Morne Lift, go back to Edgar on top of the Southeastern tower",
    "Talk to him twice",
    "Warp to Bridge of Sacrifice, go southeast to where Irina was before",
    "Talk to Edgar twice again",
    "Warp to Castle Morne Rampart",
    "Wait for Nightfall",
    "Southwest, find and defeat Deathbird",
    "Before the fight: Flask of Physicks",
    "Engage: dodge forward in between Deadbird's Legs, then use L2 — back off and Repeat",
    "<i>Sacrificial Axe</i> (cool axe, special effect: gives back FP on slaying foes)",
    "And we're done with Weeping Peninsula!",
    { t:'sec', text:"Stormveil Castle" },
    "Warp to Stormveil Cliffside",
    "Rest and level up",
    { t:'tip', text:"Stats goals: VIG 35 → END 25 → DEX 35 → STR 35" },
    "Ash of War: Select Shield → Barricade Shield → Standard",
    { t:'tip', text:"Now we can swap between the \"No Skill\" Ash of War on one of our shields and the \"Barricade Shield\" Ash of War depending on the situation" },
    "Clear the way up (you can snipe the sentinel with Bow if you want)",
    "<i>Marred Leather Shield</i> (to the left while going up the stairs)",
    "<i>Golden Rune [2]</i> (inside tower on the balcony)",
    "North at the end of corridor: <i>Hookclaws</i>",
    "Run upstairs, clear the two fire throwers",
    "North corridor next to locked door: <i>5x Throwing Dagger</i>",
    "Hole in the wall with vines: <i>10x St. Trina's Arrow</i>",
    "Rush through corridor with barrels, kill fire thrower",
    "Kill guy sitting, drop down: <i>Golden Rune [2]</i>",
    "Get back up, south corridor again, loot corpse this time: <i>3x Smoldering Butterfly</i>",
    "Go back up to where we killed guy sitting down",
    "Before opening door to the right: Lantern on + Equip Shield with Ash of War: Barricade Shield",
    "Inside this door we'll be ambushed by a strong knight, but Barricade Shield makes this really easy — a couple of Guard Counters = Stagger: <i>Rusty Key</i> (corpse), <i>Curved Sword Talisman</i> (chest)",
    "Get out the way we came from, northwest drop down to Locked Door, open it, ladder up",
    "Go right, jump over gap, clear two enemies, southeast: <i>Fire Grease</i>",
    "Jump over to platform southwest, outside catwalk kill 2 enemies and reach tower: <i>Brick Hammer</i>",
    "Go all the way back to ladder we took after the locked door, go north this time (ambush on your left)",
    "<i>Silver-Pickled Fowl Foot</i> (corpse guarded by 1 enemy)",
    "Before going up the stairs, go around ledge: <i>3x Mushroom</i>",
    "Go upstairs to defeat another Banished Knight (halberd this time, dodge his jump attack, block the rest)",
    "Go up the inside stairs, take the door to the left",
    "Activate Site of Grace: Rampart Tower but don't rest yet",
    "Small parkour time, check video: <i>3x Arteria Leaf</i>",
    "Warp back to Rampart Tower → Rest",
    "Northeast take door outside, shoot fire arrows at explosive barrels to kill 2 birds",
    "Ambush 3rd bird to your left",
    "Parkour time, check video: <i>Marred Wooden Shield</i>",
    "More parkour, drop down to trap rocks, fall down in flowers, kill scarab: <i>Ash of War: Storm Assault</i>",
    "Prepare for very strong foe, the Crucible Knight, but we're going to cheese him",
    "First hug left and loot: <i>Somber Smithing Stone [2]</i>",
    "Then drag the knight to the tower, activate the lift and roll behind it — watch him fall to his death (check video): <i>Aspect of the Crucible: Horns</i>",
    "Pull lever, but before taking the lift, outside the tower to the right: <i>Trina's Lily</i>",
    "Take the lift up: <i>2x Drawstring Fire Grease</i>",
    "Go rest at Lost Grace: Rampart Tower"
  ]
},
{
  id: 20,
  title: "Episode 20",
  steps: [
    "From Rampart Tower",
    "Kill 3 Explosive Barrel Birds",
    "Ambush 4th bird at the end with bunch of barrels: <i>Smithing Stone [2]</i>",
    "Stairs down to roof: <i>Golden Rune [2]</i>",
    "Enter bell tower, exit right, turn right again drop down on lower roof: <i>5x Kukri</i>",
    "Enter the opened window to drop down inside the chapel",
    "Talk to Rogier",
    "\"I'm here to defeat Godrick\"",
    { t:'tip', text:"You can purchase some of the Ash of War he sells if you want, but we'll be able to buy them later so save your runes if you don't intend to use those Ashes immediately" },
    "Exit church, Banished Knight patrol, snipe the torchman to have a 1v1 fight",
    "Move to next building: <i>2x Golden Rune [2]</i>",
    "Southeast walkway to next room, don't jump down",
    "Southeast door, cross to next room, kill Banished Knight (Polearm)",
    "In this room open chest: <i>Mimic Veil</i>",
    "Northeast door, beat 1 Enemy on the left, 1 more downstairs and 3 more by the fireplace: <i>Exalted Flesh</i> (under stairs)",
    "Beat the Grafted Scion in the big room (Flask of Physick — get in close melee and use Barricade / Counter): <i>Highland Axe</i>, <i>Stanching Boluses</i>",
    "North door, next room, don't take the door taking you outside, instead take the door left, go up and make your way to the item up on the catwalk: <i>10x Arrows</i>",
    "Go back to the big room",
    "Southwest door first, use elevator to fix it, go rest at the Lost Grace: Rampart Tower again — we can now use this shortcut",
    "Take elevator back down",
    "Door to the right, kill 2 dogs: <i>Golden Rune [1]</i>, <i>Crimson Hood</i>",
    "Opposite door: <i>Somber Smithing Stone [2]</i>",
    "Use Stonesword Key, beat 2 Axemen: <i>Hawk Crest Wooden Shield</i>, <i>Iron Whetblade</i>, <i>Miséricorde</i>",
    "Nothing past the other door, just an ambush",
    "Go back up the elevator",
    "Rest at grace if needed",
    "Go to the other lift with the inside stairs going up",
    "Take the stairs up, defeat 2 enemies (archer can be reached by jumping over the lift's wheel): <i>5x Throwing Daggers</i>",
    "Go opposite way, circle around the room, sneak down to take out Sentinel on the left",
    "Then a sleeping guard next to sandbags",
    "Use Sandbags to get up, time for some parkour (check video)",
    "Jump over to broken tower northeast and drop down inside tower: <i>Stonesword Key</i>",
    "Drop down with a strong attack to kill bird below you on the roof: <i>Gesture: Dozing Cross-Legged</i>",
    "2nd parkour: go to western edge of this roof and jump over to a ledge, around the tower then cross some planks to find a platform with a corpse: <i>2x Smithing Stone [2]</i>",
    "3rd parkour: go back and jump over to the next roof — climb up a broken pillar and parkour to reach next roofs with 3 archers up to the left, then 1 more patrolling",
    "Take ladder up top: <i>Claw Talisman</i>",
    "Go all the way back down to the broken pillar, this time go northeast on a small ledge and drop down to ramparts below",
    "Drop down again, get the jump on Strong Knight + Add",
    "Cross small wooden bridge kill 2 xbowmen: <i>Nomadic's Warrior Cookbook [10]</i>",
    "Ladder down southeast, kill 2 enemies",
    "Then cross the wooden bridge carefully, there's a hidden Banished Knight to the right, pull it first across the bridge to deal with it solo",
    "Then deal with the other knight (2 at the same time is risky)",
    "Once knights dead: <i>3x Festering Bloody Finger</i>",
    "Next ladder down, keep going along ramparts: <i>10x Arrows</i>",
    "Drop down again: <i>2x Golden Rune</i> (corpse at the edge, next to a fog wall)",
    "Northeast drop below, take out 4 ballista servants + Patrol xbowman: <i>Smithing Stone [2]</i>",
    "Further down: <i>Smithing Stone [1]</i>",
    "Further down take out more guards, then hug right wall — enter room, kill guard",
    "Activate Site of Grace: Gateside Chamber but don't rest at it",
    "<i>Golden Rune [5]</i>",
    "Pull Lever (main gate is now opened)",
    "East door: <i>Commoner's Garb</i>",
    "Back to previous room, drop down",
    "Talk to Gatekeeper Gostoc",
    "Exit and go through main gate: <i>Golden Rune [1]</i>, <i>Golden Rune [2]</i>, <i>5x Ballista Bolt</i>",
    "Warp back to Lost Grace: Rampart Tower",
    "LEVEL UP",
    "Spend all runes, we're about to do some dangerous parkour again",
    { t:'tip', text:"Stats goals: VIG 35 → END 25 → DEX 35 → STR 35" }
  ]
}
];

// ─── STATE ───────────────────────────────────────────────────
const KEY = 'er_guide_v1';
let S = {};
function load() { try { S = JSON.parse(localStorage.getItem(KEY)) || {}; } catch { S = {}; } }
function save() { localStorage.setItem(KEY, JSON.stringify(S)); }
function isRevealed(eid, idx) { return !!(S[eid] && S[eid].r && S[eid].r[idx]); }
function isDone(eid, idx)     { return !!(S[eid] && S[eid].d && S[eid].d[idx]); }
function setRevealed(eid, idx) {
  if (!S[eid]) S[eid] = {};
  if (!S[eid].r) S[eid].r = {};
  S[eid].r[idx] = true; save();
}
function toggleDone(eid, idx) {
  if (!S[eid]) S[eid] = {};
  if (!S[eid].d) S[eid].d = {};
  S[eid].d[idx] = !S[eid].d[idx]; save();
}
function resetAll() {
  if (!confirm('Reset all progress?')) return;
  S = {}; save(); render();
}
function resetEp(id) {
  if (!confirm('Reset progress for this episode?')) return;
  delete S[id]; save();
  const openEps = [...document.querySelectorAll('.ep.open')].map(e => e.id);
  render();
  openEps.forEach(id => { const el = document.getElementById(id); if(el) el.classList.add('open'); });
}

// ─── RENDER ──────────────────────────────────────────────────
function render() {
  load();
  const app = document.getElementById('app');
  app.innerHTML = '';

  EPS.forEach(ep => {
    const checks = ep.steps.map((s,i) => typeof s === 'string' ? i : null).filter(i => i !== null);
    const epDone = checks.filter(i => isDone(ep.id, i)).length;
    const complete = epDone === checks.length && checks.length > 0;

    const div = document.createElement('div');
    div.className = 'ep' + (epDone > 0 ? ' has-done' : '') + (complete ? ' complete' : '');
    div.id = 'ep' + ep.id;

    let content = '<div class="ep-inner">';
    ep.steps.forEach((s, idx) => {
      if (typeof s === 'object') {
        if (s.t === 'sec')  content += `<div class="sec">${s.text}</div>`;
        if (s.t === 'warn') content += `<div class="warn">${s.text}</div>`;
        if (s.t === 'tip')  content += `<div class="tip">${s.text}</div>`;
      } else {
        const revealed = isRevealed(ep.id, idx);
        const done_    = isDone(ep.id, idx);
        const cls = done_ ? 'done' : (!revealed ? 'hidden' : '');
        content += `<div class="step ${cls}" data-ep="${ep.id}" data-idx="${idx}">
          <div class="cb"></div>
          <div class="step-txt">${s}</div>
        </div>`;
      }
    });
    content += '</div>';

    div.innerHTML = `
      <div class="ep-hdr" onclick="toggleEp(${ep.id})">
        <div class="ep-num">EP<br>${String(ep.id).padStart(2,'0')}</div>
        <div class="ep-name">${ep.title}</div>
        <div class="ep-stat ${complete ? 'ok' : ''}"></div>
        ${epDone > 0 ? `<button class="btn-ep-rst" onclick="event.stopPropagation();resetEp(${ep.id})">Reset</button>` : ''}
        <div class="ep-arr">▶</div>
      </div>
      <div class="ep-body">${content}</div>`;

    app.appendChild(div);
  });

  document.querySelectorAll('.step').forEach(el => {
    el.addEventListener('click', () => {
      const eid = +el.dataset.ep, idx = +el.dataset.idx;
      if (el.classList.contains('hidden')) {
        setRevealed(eid, idx);
      } else {
        toggleDone(eid, idx);
      }
      const openEps = [...document.querySelectorAll('.ep.open')].map(e => e.id);
      render();
      openEps.forEach(id => { const el = document.getElementById(id); if(el) el.classList.add('open'); });
    });
  });
}

function toggleEp(id) {
  document.getElementById('ep' + id).classList.toggle('open');
}

load(); render();
